# These are supported funding model platforms

github: [astronomizedev]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: consoletint
liberapay: # Replace with a single Liberapay username
issuehunt: consoletint/ConsoleTint
